[package]
name = "vk_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ozy_engine = { path = "../ozy_engine" }
nalgebra-glm = "*"
wasapi = "0.1.2"

[dependencies.ash]
version = "*"
features = ["linked"]

[dependencies.sdl2]
version = "*"
features = ["bundled", "raw-window-handle"]